# Generated by Django 2.2.4 on 2019-08-09 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20190808_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 17, 48, 4, 103078, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 17, 48, 4, 102341, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='', max_length=140),
        ),
    ]
