# Generated by Django 2.2.4 on 2019-08-10 23:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20190810_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 23, 28, 34, 388629, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 23, 28, 34, 387920, tzinfo=utc)),
        ),
    ]
