# Generated by Django 2.2.4 on 2019-08-09 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20190809_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 18, 24, 36, 52954, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 18, 24, 36, 52375, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
